
enum Digit{ ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE};

enum Operator{ SUM, SUBTRACTION, DIVISION, MULTIPLICATION, PERCENTAGE, SQUARE_ROOT};

enum Control{ ON, OFF, CLEAR_ERROR, MEMORY_READ_CLEAR, MEMORY_SUM, MEMORY_SUBTRACTION, EQUAL, DECIMAL_SEPARATOR};
